Repository dotnet/installer, pull requests merged in 2019-10, with the labels that each got.

#5021 [release/3.0.1xx] React to 3.0 dev channel removal
  .vsts-ci.yml
Labels: tell-mode

#5042 Template versioning needs to flow into core-sdk
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#5067 Fix typo causing 3.1 ASP.NET runtime pack to not be found
  src/redist/targets/GenerateBundledVersions.targets
  test/EndToEnd/ProjectBuildTests.cs
Labels: Approved to merge

#5090 Enabling ASP.NET in RPM/DEB native installers
  src/redist/targets/GenerateDebs.targets
  src/redist/targets/GenerateRPMs.targets
  src/redist/targets/packaging/deb/dotnet-debian_config.json
  src/redist/targets/packaging/rpm/dotnet-config.json
Labels: area-Setup

#5082 Prepare for 3.0.101 servicing
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/configure-toolset.ps1
  eng/configure-toolset.sh
  src/core-sdk-tasks/GetLinuxNativeInstallerDependencyVersions.cs
  src/redist/redist.csproj
  src/redist/targets/Branding.targets
  src/redist/targets/BuildCoreSdkTasks.targets
  src/redist/targets/BundledTemplates.targets
  src/redist/targets/Crossgen.targets
  src/redist/targets/GenerateBundledVersions.targets
  src/redist/targets/GenerateDebs.targets
  src/redist/targets/GenerateLayout.targets
  src/redist/targets/GenerateMSIs.targets
  src/redist/targets/GeneratePKG.targets
  src/redist/targets/GenerateRPMs.targets
  src/redist/targets/LinuxNativeInstallerDependencyVersions.targets
  src/redist/targets/packaging/deb/dotnet-debian_config.json
  src/redist/targets/packaging/rpm/dotnet-config.json
Labels: Servicing-approved

#5294 Updating the VS warning
  src/redist/targets/packaging/windows/clisdk/LCID/1028/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1029/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1031/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1033/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1036/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1040/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1041/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1042/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1045/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1046/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1049/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1055/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/2052/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/3082/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/bundle.wxs
Labels: area-Setup

#5295 Increase button width
  src/redist/targets/packaging/windows/clisdk/bundle.thm
Labels: area-Setup

#5302 [3.0] Pass timeout along
  eng/build.yml
Labels: Area-Infrastructure, tell-mode

#5308 Download shared runtime archive from correct blob location
  src/redist/targets/GenerateLayout.targets
Labels: tell-mode

#5338 Remove old style restore sources
  eng/Versions.props
Labels: tell-mode
