Repository dotnet/installer, pull requests merged in 2019-11, with the labels that each got.

#5416 Update dockers porting to 3.0.1xx
  .vsts-ci.yml
  eng/docker/debian/Dockerfile
  eng/docker/fedora.23/Dockerfile
  eng/docker/fedora.24/Dockerfile
  eng/docker/fedora.27/Dockerfile
  eng/docker/fedora.28/Dockerfile
  eng/docker/rhel.6/Dockerfile
  eng/docker/ubuntu.14.04/Dockerfile
  netci.groovy
  src/redist/targets/Badge.targets
  src/redist/targets/GenerateLayout.targets
  src/redist/targets/GetRuntimeInformation.targets
  src/redist/targets/SetBuildDefaults.targets
  test/SdkTests/SdkTests.csproj
Labels: tell-mode

#5577 [release/3.1.1xx] Merge from release/3.0.1xx
  eng/Version.Details.xml
  eng/Versions.props
  src/redist/targets/GenerateBundledVersions.targets
  src/redist/targets/GenerateLayout.targets
  test/Microsoft.DotNet.Tools.Tests.Utilities/Commands/TestCommand.cs
Labels: tell-mode

#5610 Revert "Remove rhel.6"
  .vsts-ci.yml
  eng/docker/rhel.6/Dockerfile
  src/redist/targets/Badge.targets
  src/redist/targets/GenerateLayout.targets
  src/redist/targets/GetRuntimeInformation.targets
  src/redist/targets/SetBuildDefaults.targets
Labels: tell-mode

#5686 Updating the 3.0 templates from "3.0.0" to "3.0.1"
  NuGet.config
  eng/Versions.props
Labels: Servicing-approved, area-Setup

#5698 Bump 3.0 packs to 3.0.1 as appropriate
  NuGet.config
  src/redist/targets/GenerateBundledVersions.targets
Labels: ask-mode

#5634 NUnit3Templates update
  eng/Versions.props
Labels: ask-mode
