Repository dotnet/installer, pull requests merged in 2019-09, with the labels that each got.

#4549 Setup updates for release/3.1.1xx
  src/redist/targets/Branding.targets
  src/redist/targets/GenerateMSIs.targets
  src/redist/targets/Signing.targets
  src/redist/targets/packaging/windows/clisdk/VS.Redist.Common.NetCore.Toolset.nuspec
  src/redist/targets/packaging/windows/clisdk/dotnet.wxs
  src/redist/targets/packaging/windows/clisdk/generatenupkg.ps1
Labels: area-Setup

#4568 Localization update for PTB runtime term changes.
  src/redist/targets/packaging/windows/clisdk/LCID/1046/bundle.wxl
Labels: area-Setup, ask-mode

#4706 Download the ASP.NET SharedFramework MSI and the Module V2 MSI
  src/redist/targets/GenerateLayout.targets
  src/redist/targets/GenerateMSIs.targets
Labels: Area-Infrastructure, area-Setup

#4638 LOC update for zh-cn and zh-tw
  src/redist/targets/packaging/windows/clisdk/LCID/1028/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/2052/bundle.wxl
Labels: area-Setup, ask-mode

#4734 [source-build] Allow differing core runtime and ASP.NET runtime RIDs.
  src/redist/targets/GenerateLayout.targets
Labels: tell-mode

#4867 [release/3.0.1xx] Remove generate graph files
  .vsts-ci.yml
Labels: tell-mode

#4931 Add 3.1 Templates MSIs
  eng/Versions.props
  src/redist/targets/Branding.targets
  src/redist/targets/BundledTemplates.targets
  src/redist/targets/GenerateMSIs.targets
Labels: area-Setup
