Repository dotnet/installer, pull requests merged in 2019-08, with the labels that each got.

#3826 Update sdk bundle links
  src/redist/targets/packaging/windows/clisdk/LCID/1033/bundle.wxl
Labels: area-Setup

#3872 Updating the .NET Core installer welcome message.
  src/redist/targets/packaging/windows/clisdk/LCID/1033/bundle.wxl
Labels: area-Setup

#3742 Remove unused variables from bundled versions
  src/redist/targets/GenerateBundledVersions.targets
Labels: tell-mode

#3901 Removing the RelativeLayoutPath: "shared"; master
  src/redist/targets/GenerateLayout.targets
Labels: Area-Infrastructure

#3902 Removing the RelativeLayoutPath: "shared"; 3.0.1xx
  src/redist/targets/GenerateLayout.targets
Labels: Area-Infrastructure

#3812 update dotnet new nunit bundled templates to v1.6.3
  eng/Versions.props
Labels: Approved to merge, ask-mode

#3982 LOC CHECKIN | dotnet/core-sdk master | 20190813
  src/redist/targets/packaging/windows/clisdk/LCID/1028/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1029/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1031/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1036/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1040/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1041/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1042/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1045/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1046/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1049/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1055/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/2052/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/3082/bundle.wxl
Labels: tell-mode
