Repository dotnet/installer, pull requests merged in 2020-10, with the labels that each got.

#8808 Update to Windows SDK projection to drop preview tag
  eng/ManualVersions.props
Labels: Auto-Merge If Tests Pass, auto-merge

#8813 Update template/31 versions
  eng/Versions.props
  src/redist/targets/GenerateBundledVersions.targets
Labels: Servicing-consider

#8848 Update branding for 110
  src/redist/targets/GenerateBundledVersions.targets
  src/redist/targets/Versions.targets
Labels: Branding

#8847 Update branding for 404
  src/redist/targets/GenerateBundledVersions.targets
  src/redist/targets/Versions.targets
Labels: Branding

#8960 Revert implicit version updates
  src/redist/targets/GenerateBundledVersions.targets
Labels: Auto-Merge If Tests Pass, auto-merge
