Repository dotnet/installer, pull requests merged in 2020-05, with the labels that each got.

#7372 Update channel definition
  eng/common/templates/post-build/post-build.yml
Labels: Auto-Merge If Tests Pass, auto-merge

#7463 Change to correct channel
  src/CopyToLatest/targets/BranchInfo.props
Labels: Auto-Merge If Tests Pass, auto-merge

#7480 Update 3.1.3xx branding
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/redist/targets/GenerateBundledVersions.targets
  src/redist/targets/Versions.targets
Labels: Auto-Merge If Tests Pass, auto-merge

#7514 Port #7457 (Add arm64 as a possible WinForms arch) to preview 5
  src/redist/targets/GenerateBundledVersions.targets
  src/redist/targets/GenerateLayout.targets
  test/EndToEnd/ProjectBuildTests.cs
Labels: Servicing-consider

#7552 Add CPD attributes to installer
  eng/Version.Details.xml
  eng/Versions.props
Labels: auto-merge
