Repository dotnet/installer, pull requests merged in 2020-01, with the labels that each got.

#6143 Bump 2.1.x implicit versions
  src/redist/targets/GenerateBundledVersions.targets
  test/EndToEnd/GivenSelfContainedAppsRollForward.cs
  test/SdkTests/TestConfig.xml
Labels: Area-Infrastructure, tell-mode

#6235 core-setup -> runtime
  README.md
Labels: Auto-Merge If Tests Pass, auto-merge

#6242 Fix msi non-deterministic ComponentId
  Microsoft.DotNet.Cli.sln
  src/core-sdk-tasks/CalculateTemplateVersions.cs
  src/redist/targets/BuildCoreSdkTasks.targets
  src/redist/targets/BundledTemplates.targets
  src/redist/targets/packaging/windows/clisdk/generatemsi.ps1
  src/redist/targets/packaging/windows/clisdk/generatetemplatesmsi.ps1
  test/core-sdk-tasks.Tests/CalculateTemplateVerionsTests.cs
  test/core-sdk-tasks.Tests/core-sdk-tasks.Tests.csproj
Labels: Auto-Merge If Tests Pass, auto-merge

#6245 Fix msi gg release/3.1.1xx
  Microsoft.DotNet.Cli.sln
  src/core-sdk-tasks/CalculateTemplateVersions.cs
  src/redist/targets/BuildCoreSdkTasks.targets
  src/redist/targets/BundledTemplates.targets
  src/redist/targets/packaging/windows/clisdk/generatemsi.ps1
  src/redist/targets/packaging/windows/clisdk/generatetemplatesmsi.ps1
  test/core-sdk-tasks.Tests/CalculateTemplateVerionsTests.cs
  test/core-sdk-tasks.Tests/core-sdk-tasks.Tests.csproj
Labels: Servicing-consider

#6244 Fix msi gg release/3.0.1xx
  Microsoft.DotNet.Cli.sln
  src/core-sdk-tasks/CalculateTemplateVersions.cs
  src/redist/targets/BuildCoreSdkTasks.targets
  src/redist/targets/BundledTemplates.targets
  src/redist/targets/packaging/windows/clisdk/generatemsi.ps1
  src/redist/targets/packaging/windows/clisdk/generatetemplatesmsi.ps1
  test/core-sdk-tasks.Tests/CalculateTemplateVerionsTests.cs
  test/core-sdk-tasks.Tests/core-sdk-tasks.Tests.csproj
Labels: Auto-Merge If Tests Pass, Servicing-consider, auto-merge
