Repository dotnet/installer, pull requests merged in 2020-08, with the labels that each got.

#8141 Dev/merge internal 08112020/release/3.1.1xx
  eng/Version.Details.xml
  eng/Versions.props
  src/redist/targets/GenerateBundledVersions.targets
  src/redist/targets/Versions.targets
Labels: Branding

#8155 Dev/merge internal 08132020/release/3.1.4xx
  eng/Version.Details.xml
  eng/Versions.props
  src/redist/targets/GenerateBundledVersions.targets
  src/redist/targets/Versions.targets
Labels: Branding

#8160 Fixup license paths
  src/redist/targets/packaging/windows/clisdk/generatemsi.ps1
  src/redist/targets/packaging/windows/clisdk/generatesdkplaceholdermsi.ps1
  src/redist/targets/packaging/windows/clisdk/generatetemplatesmsi.ps1
Labels: Auto-Merge If Tests Pass, auto-merge

#8157 [release/5.0.1xx-preview8] Update min VS version in installer info
  src/redist/targets/packaging/windows/clisdk/LCID/1028/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1029/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1031/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1033/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1036/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1040/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1041/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1042/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1045/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1046/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1049/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/1055/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/2052/bundle.wxl
  src/redist/targets/packaging/windows/clisdk/LCID/3082/bundle.wxl
Labels: Auto-Merge If Tests Pass, auto-merge

#8164 Update implicit version for 3.1 runtime
  src/redist/targets/GenerateBundledVersions.targets
Labels: Area-Infrastructure

#8205 Move few GivenWeWantToRequireWindowsForDesktopApps tests
  test/EndToEnd/GivenWeWantToRequireWindowsForDesktopApps.cs
  test/EndToEnd/TestProjectCreator.cs
  test/Microsoft.DotNet.Tools.Tests.Utilities/PlatformSpecificFact.cs
  test/Microsoft.DotNet.Tools.Tests.Utilities/PlatformSpecificTheory.cs
Labels: Auto-Merge If Tests Pass, auto-merge
