Repository dotnet/installer, pull requests merged in 2020-09, with the labels that each got.

#8383 Pin Xdt until strict coherency is enabled
  eng/Version.Details.xml
Labels: Auto-Merge If Tests Pass, auto-merge

#8357 Update README.md to include link to https://github.com/dotnet/install-scripts
  README.md
Labels: Auto-Merge If Tests Pass, auto-merge

#8426 Add 3.1 Blazor WASM templates
  eng/Versions.props
  src/redist/targets/BundledTemplates.targets
Labels: Servicing-consider

#8459 Update branding to 3.1.109
  src/redist/targets/GenerateBundledVersions.targets
  src/redist/targets/Versions.targets
Labels: Branding

#8576 React to non-stable versioning of AspNetCore installers
  eng/Version.Details.xml
  eng/Versions.props
  src/redist/targets/GenerateLayout.targets
Labels: tell-mode

#8586 Add VSTemplateLocator package
  eng/Versions.props
  src/VSTemplateLocator/VSTemplateLocator.csproj
  src/redist/redist.csproj
  src/redist/targets/GenerateMSIs.targets
  src/redist/targets/packaging/windows/clisdk/VS.Redist.Common.Net.Core.SDK.VSTemplateLocator.nuspec
Labels: Auto-Merge If Tests Pass, auto-merge

#8611 Update microsoft.windows.sdk.net.ref
  eng/ManualVersions.props
  eng/Versions.props
Labels: Auto-Merge If Tests Pass, auto-merge

#8672 Do not produce reference assembly for redist.dll
  src/redist/redist.csproj
Labels: Area-Infrastructure

#8711 Update installer to rtm branding
  eng/Versions.props
Labels: Branding
