Repository dotnet/installer, pull requests merged in 2020-12, with the labels that each got.

#9205 Update branding to 5.0.102
  eng/Versions.props
Labels: Auto-Merge If Tests Pass, auto-merge

#9222 [release/5.0.2xx] Enable linux-musl-arm* builds in CI
  .vsts-ci.yml
  src/redist/targets/Crossgen.targets
  src/redist/targets/GenerateBundledVersions.targets
  src/redist/targets/GenerateLayout.targets
  src/redist/targets/GetRuntimeInformation.targets
  src/redist/targets/SetBuildDefaults.targets
Labels: auto-merge

#9229 Update README.md and table generator for linux-musl-arm
  README.md
  tools/sdk-readme-table-generator/TableGenerator.Tests/DomainTests.fs
  tools/sdk-readme-table-generator/TableGenerator/Reference.fs
  tools/sdk-readme-table-generator/TableGenerator/Shared.fs
  tools/sdk-readme-table-generator/TableGenerator/Table.fs
Labels: area-Setup
