Repository dotnet/installer, pull requests merged in 2020-02, with the labels that each got.

#6511 Update to 3.1.2 runtime
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/redist/targets/GenerateLayout.targets
Labels: Auto-Merge If Tests Pass, auto-merge

#6546 Add 5.0 common project templates to Bundle.
  eng/Versions.props
  src/redist/targets/BundledTemplates.targets
  test/EndToEnd/ProjectBuildTests.cs
Labels: Auto-Merge If Tests Pass, auto-merge

#6594 No suffix
  src/redist/targets/Versions.targets
Labels: Area-Infrastructure, auto-merge

#6597 Fix no "latest" -- Update publish depends on
  .vsts-ci.yml
Labels: Area-Infrastructure

#6610 Bump self-contained default for 3.0.x and 2.1.x
  NuGet.config
  src/redist/targets/GenerateBundledVersions.targets
Labels: Auto-Merge If Tests Pass, auto-merge
