Repository dotnet/installer, pull requests merged in 2021-01, with the labels that each got.

#9365 Update branding for 103
  eng/Versions.props
Labels: Branding

#9475 Fix linux-musl-arm apphost
  src/redist/targets/GenerateBundledVersions.targets
Labels: area-Setup

#9510 Updating branding from 6.0.100 alpha to preview
  eng/Versions.props
Labels: Auto-Merge If Tests Pass, Branding, auto-merge

#9539 Sign dotnet-watch files
  src/redist/targets/Signing.targets
Labels: Auto-Merge If Tests Pass, auto-merge

#9514 Installer text improvements
  src/redist/targets/packaging/windows/clisdk/LCID/1033/bundle.wxl
Labels: Approved to merge, Auto-Merge If Tests Pass, auto-merge
