Repository dotnet/installer, pull requests merged in 2021-02, with the labels that each got.

#9595 Update 5.0.3xx branding
  eng/Versions.props
Labels: Auto-Merge If Tests Pass, auto-merge

#9653 Update branding for 3.1.4xx 3.1.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/redist/targets/GenerateLayout.targets
  src/redist/targets/Versions.targets
Labels: Branding

#9631 Remove usage of dotnet-deb-tool
  src/core-sdk-tasks/DotNetDebTool.cs
  src/redist/redist.csproj
  src/redist/targets/GenerateDebs.targets
  src/redist/targets/GenerateMSIs.targets
Labels: Area-Infrastructure

#9654 Update branding for 3.1.1xx 3.1.1xx
  src/redist/targets/Versions.targets
Labels: Branding

#9652 Update branding for 5.0.1xx 5.0.1xx
  eng/Versions.props
Labels: Branding

#9736 Update branding and implicit version
  eng/Versions.props
  src/redist/targets/GenerateBundledVersions.targets
Labels: Auto-Merge If Tests Pass, auto-merge

#9778 Update Versions.props
  eng/Versions.props
Labels: Auto-Merge If Tests Pass, auto-merge
