Repository dotnet/installer, pull requests merged in 2021-03, with the labels that each got.

#9796 Update branding for 3.1.4xx 3.1.4xx
  src/redist/targets/Versions.targets
Labels: Branding

#9842 Update the version table
  README.md
  tools/sdk-readme-table-generator/TableGenerator/Program.fs
  tools/sdk-readme-table-generator/TableGenerator/Reference.fs
  tools/sdk-readme-table-generator/TableGenerator/Shared.fs
Labels: Auto-Merge If Tests Pass, auto-merge

#9798 Update branding for 5.0.2xx 5.0.2xx
  eng/Versions.props
  test/EndToEnd/GivenWeWantToRequireWindowsForDesktopApps.cs
  test/SdkTests/TestConfig.xml
Labels: Auto-Merge If Tests Pass, Branding, auto-merge

#9920 Update branding for 5.0.1xx 5.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Branding

#9919 Update branding for 3.1.1xx 3.1.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Branding

#9918 Update branding for 3.1.4xx 3.1.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/redist/targets/GenerateLayout.targets
Labels: Branding

#9904 Merge internal changes for 5.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/build.yml
  src/redist/targets/GenerateLayout.targets
Labels: Branding

#10026 Fix official build
  eng/Publishing.props
  src/redist/targets/Badge.targets
  src/redist/targets/GenerateBundledVersions.targets
Labels: auto-merge

#10029 Rename iOS simulator targets from 'ios' to 'iossimulator' RID
  src/redist/targets/GenerateBundledVersions.targets
Labels: auto-merge

#10079 Update 5.0.3xx implicit versions
  src/redist/targets/GenerateBundledVersions.targets
Labels: Auto-Merge If Tests Pass, auto-merge
