Repository dotnet/installer, pull requests merged in 2021-06, with the labels that each got.

#10817 Update branding for 3.1.1xx 3.1.1xx
  src/redist/targets/Versions.targets
Labels: Branding

#10818 Update branding for 3.1.4xx 411
  src/redist/targets/Versions.targets
Labels: Branding

#10820 Update branding for 5.0.2xx to 205
  eng/Versions.props
Labels: Branding

#10819 Update branding for 5.0.3xx to 302
  eng/Versions.props
Labels: Branding

#10823 Update aspnetcore 3.1 & 5.0 template versions
  eng/Versions.props
  src/redist/targets/GenerateBundledVersions.targets
Labels: Auto-Merge If Tests Pass, auto-merge

#10947 Modify GenerateLayout to work with runtime configs that contain more than one runtime (#10901)
  src/core-sdk-tasks/UpdateRuntimeConfig.cs
  src/redist/targets/BuildCoreSdkTasks.targets
  src/redist/targets/GenerateLayout.targets
Labels: Servicing-consider
