Repository dotnet/installer, pull requests merged in 2022-03, with the labels that each got.

#12790 Fix the logic that generates the fallback text file
  src/redist/targets/GenerateLayout.targets
Labels: Servicing-approved

#13362 [5.0.2xx] Bump aspnetcore template version
  eng/Versions.props
Labels: tell-mode, dependencies

#13364 [5.0.4xx] Bump aspnetcore template version
  eng/Versions.props
Labels: tell-mode, dependencies

#13365 [6.0.1xx] Bump aspnetcore template versions
  eng/Versions.props
Labels: tell-mode, dependencies

#13366 [6.0.2xx] Bump aspnetcore template versions
  eng/Versions.props
Labels: tell-mode, dependencies

#13367 [6.0.3xx] Bump aspnetcore template versions
  eng/Versions.props
Labels: tell-mode, dependencies

#13368 [main] Bump aspnetcore template versions
  eng/Versions.props
  src/redist/targets/GenerateBundledVersions.targets
Labels: dependencies

#13390 Remove maui workloads from 6.0.100
  src/redist/targets/BundledManifests.targets
Labels: Servicing-approved, Servicing-consider
