Repository dotnet/installer, pull requests merged in 2022-08, with the labels that each got.

#14266 Stop app host downloads for android
  src/redist/targets/GenerateBundledVersions.targets
Labels: Servicing-approved

#14245 [6.0.4xx] Update template versions from dotnet/aspnetcore
  eng/Versions.props
Labels: Area-Infrastructure, tell-mode

#14243 [6.0.1xx] Update template versions from dotnet/aspnetcore
  eng/Versions.props
Labels: Area-Infrastructure, tell-mode

#14244 [6.0.3xx] Update template versions from dotnet/aspnetcore
  eng/Versions.props
Labels: Area-Infrastructure, tell-mode

#14246 [main] Update template versions from dotnet/aspnetcore
  eng/Versions.props
  src/redist/targets/GenerateBundledVersions.targets
Labels: Area-Infrastructure

#14276 Add the full nuget version into the .version file
  src/redist/targets/GenerateLayout.targets
Labels: Servicing-approved
