Repository dotnet/installer, pull requests merged in 2024-04, with the labels that each got.

#18883 [VMR] Try lighting up ARM32/ARM64 lanes
  eng/pipelines/templates/stages/vmr-build.yml
  eng/pipelines/templates/variables/vmr-build.yml
  src/SourceBuild/content/test/Microsoft.DotNet.UnifiedBuild.Tests/assets/baselines/MsftToUbSdkAssemblyVersions-linux-arm.diff
  src/SourceBuild/content/test/Microsoft.DotNet.UnifiedBuild.Tests/assets/baselines/MsftToUbSdkAssemblyVersions-linux-arm64.diff
  src/SourceBuild/content/test/Microsoft.DotNet.UnifiedBuild.Tests/assets/baselines/MsftToUbSdkFiles-linux-arm.diff
  src/SourceBuild/content/test/Microsoft.DotNet.UnifiedBuild.Tests/assets/baselines/MsftToUbSdkFiles-linux-arm64.diff
Labels: Area-SourceBuild

#19355 [VMR] Light up NativeAOT OSX short lanes
  eng/pipelines/templates/stages/vmr-build.yml
  src/SourceBuild/content/Directory.Build.props
Labels: Area-SourceBuild

#19399 Redo "NGEN Microsoft.DotNet.MSBuildSdkResolver.dll and its dependencies" for devenv only
  src/core-sdk-tasks/GenerateMSBuildExtensionsSWR.cs
Labels: Servicing-approved

#19405 Update WiX to 3.14.1.8722
  eng/Versions.props
Labels: Servicing-approved

#19415 Update WiX to 3.14.1.8722
  eng/Versions.props
Labels: Servicing-approved

#19417 Update WiX to 3.14.1.8722
  eng/Versions.props
Labels: Servicing-approved

#19416 Update WiX to 3.14.1.8722
  eng/Versions.props
Labels: Servicing-approved

#19408 Update WiX to 3.14.1.8722
  eng/Versions.props
Labels: Servicing-approved

#19409 Update WiX to 3.14.8722
  eng/Versions.props
Labels: Servicing-approved

#19410 Update WiX to 3.14.1.8722
  eng/Versions.props
Labels: Servicing-approved

#19406 Update WiX to 3.14.1.8722
  eng/Versions.props
Labels: Servicing-approved

#19407 Update WiX to 3.14.1.8722
  eng/Versions.props
Labels: Servicing-approved

#19477 Allow test databases in the VMR build and add license suppressions for efcore
  src/SourceBuild/content/eng/allowed-vmr-binaries.txt
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/LicenseExclusions.txt
Labels: Area-SourceBuild

#19433 Build the SourceBuilt tarball in the publish job and include the merged vertical manifest in it.
  src/SourceBuild/content/Directory.Build.props
  src/SourceBuild/content/eng/finish-source-only.proj
  src/SourceBuild/content/eng/publish.proj
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/content/repo-projects/installer.proj
Labels: Area-SourceBuild

#19544 [release/8.0.1xx] Source-build dotnet/runtime patch: crashinfo.cpp/crasinfounix.cpp: use off_t instead of off64_t
  src/SourceBuild/patches/runtime/0001-crashinfo-use-off_t-instead-of-off64_t.patch
Labels: Servicing-consider, Area-SourceBuild
