Repository dotnet/installer, pull requests merged in 2024-05, with the labels that each got.

#19755 [release/9.0.1xx-preview4] Rollback Aspire version to shipped 9.0 preview 3
  eng/Version.Details.xml
  eng/Versions.props
Labels: Servicing-approved

#19829 [release/8.0.1xx-staging] Remove PGO builds
  .vsts-ci.yml
Labels: Servicing-consider, Area-Infrastructure

#19830 [release/8.0.3xx-staging] Remove PGO builds
  .vsts-ci.yml
Labels: Area-Infrastructure
