Repository dotnet/installer, pull requests merged in 2024-02, with the labels that each got.

#18173 Enable error on prebuilts
  src/SourceBuild/content/eng/Versions.props
  src/SourceBuild/content/eng/build.sourcebuild.targets
Labels: Area-SourceBuild

#18266 Add install state cleanup to finalizer
  src/finalizer/CMakeLists.txt
  src/finalizer/finalizer.cpp
  src/finalizer/precomp.h
Labels: Servicing-approved

#18680 Update branding again and downgrade implicit version
  eng/Versions.props
Labels: Branding

#18672 Add VMR support for Windows-x64 PGO Instrumented leg
  eng/SourceBuild.props
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/stages/vmr-build.yml
  src/SourceBuild/content/Directory.Build.props
  src/SourceBuild/content/repo-projects/Directory.Build.targets
  src/SourceBuild/content/repo-projects/installer.proj
  src/SourceBuild/content/repo-projects/runtime.proj
  src/SourceBuild/content/repo-projects/source-build-reference-packages.proj
Labels: DO NOT MERGE
